### ISSUE TITLE
Problème d'export d'un profil

### ISSUE THREAD

**Issue by lherry** [florian-mollin/loto-associatif-app#1]
Bonjour,

Je rencontre un souci avec l'export de la configuration qui semble ne pas fonctionner.
L'export me propose de choisir un dossier, mais après sélection rien ne se produit : pas d'erreur ni de dialogue m'indiquant l'export du profil sélectionné. Dans le dossier, aucun fichier n'est créé.

Merci.

**Comment by florian-mollin** [comment]
Bonjour,

J'imagine que vous avez téléchargé l’exécutable à partir du site web, il y a en effet eu un problème lors de la génération de celui-ci (je n'ai pas pris le temps de vérifier la partie import/export), donc l’exécutable n’était pas pleinement fonctionnel.
Merci de me l'avoir signalé, normalement je viens de mettre le site à jour, vous pouvez donc de nouveau télécharger l’exécutable sur le site : https://florian-mollin.github.io/loto-associatif/#telechargements et il ne devrait plus y avoir de problèmes.
N'hésitez pas si vous rencontrez d'autres problèmes ou que vous avez des idées d'améliorations.

PS : si tout fonctionne de votre coté, tenez moi au courant que je ferme l'issue.

**Comment by lherry** [comment]
Bonjour,

Merci de votre retour et de votre réactivité !
Effectivement, j'avais téléchargé l'installateur exécutable depuis le portail principal...
Je viens donc de le re-télécharger et la partie export semble fonctionner !
Je n'ai toutefois pas encore re testé l'ensemble de l'application.

Merci en tous cas pour cette application sobre, simple et efficace,
