### ISSUE TITLE
Modification nombre de boule

### ISSUE THREAD

**Issue by Antoine26200** [florian-mollin/loto-associatif-app#2]
Hello,
Je me demandais s'il était possible de modifier le nombre de boule. 
En effet, ma compagne a organisé un loto entre amis, et nous avons un boulier de 75 boules et non de 90. 
Y a t'il un moyen de changer ça dans le code ? 

Cordialement,
Antoine

**Comment by florian-mollin** [comment]
Bonjour,
Actuellement ce n'est possible désolé. (et pour être franc, ce n'est pas prévu)
Merci,
